[package]
name = "libsql_bench"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tokio"
path = "src/tokio.rs"

[[bin]]
name = "libsql"
path = "src/libsql.rs"

[dependencies]
tokio = {version  = "^1.38.0", features=["macros", "rt-multi-thread"] }
tokio-rusqlite = "0.5.1"
libsql = "0.3.5"

rusqlite = { version = "^0.31.0", features=[
    "column_decltype",
    "load_extension",
    "modern_sqlite",
    "functions",
    "limits",
] }
