[package]
name = "rusqlite_thread_local_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
constants = { path = "../constants" }
parking_lot = "0.12.3"
rusqlite = "0.32.1"
tempfile = "3.14.0"
tokio = {version  = "^1.38.0", features=["macros", "rt-multi-thread"] }
