[package]
name = "libsql_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = "3.14.0"
tokio = {version  = "^1.38.0", features=["macros", "rt-multi-thread"] }
tokio-rusqlite = "0.6.0"
