[package]
name = "tokio_rusqlite_bench"
version = "0.1.0"
edition = "2021"

[dependencies]
constants = { path = "../constants" }
tempfile = "3.14.0"
tokio = {version  = "^1.38.0", features=["macros", "rt-multi-thread"] }
tokio-rusqlite = { path = "../vendor/tokio-rusqlite/" }
