[package]
name = "rusqlite_thread_local_bench2"
version = "0.1.0"
edition = "2021"

[dependencies]
constants = { path = "../constants" }
rusqlite = "0.34.0"
tempfile = "3.14.0"
thread_local = "1.1.8"
tokio = {version  = "^1.38.0", features=["macros", "rt-multi-thread"] }
